#Esto es una REGLA cada regla tiene la siguiente estructura:

objetivo: dependencias
		instrucciones

#objetivo: es el nombre por el cual vamos a llamar a esta
# regla por consola

#dependencias: archivos de los que va a depender para
# realizar su tarea,por ejemplo archivos.o u otra regla

#intrucciones: intrucciones de codigo que va a seguir
# para cumplir la tarea por la que fue creada, ej compilar
# un archivo con gcc